const soalData = [
  {
    name: "Free Try Out",
    jumlahSoal: 150,
    status: "Open",
    waktu: "100",
    tanggal: "12 Juli 2025",
  },
  {
    name: "Try Out Materi SBA",
    jumlahSoal: 100,
    status: "Hold",
    waktu: "100",
    tanggal: "27 Juli 2025",
  },
  {
    name: "Try Out SMA 2025",
    jumlahSoal: 120,
    status: "Open",
    waktu: "90",
    tanggal: "2 Agustus 2025",
  },
  {
    name: "Try Out Matematika Dasar",
    jumlahSoal: 110,
    status: "Open",
    waktu: "80",
    tanggal: "5 Agustus 2025",
  },
  {
    name: "Try Out Fisika",
    jumlahSoal: 130,
    status: "Open",
    waktu: "100",
    tanggal: "7 Agustus 2025",
  },
  {
    name: "Try Out Biologi",
    jumlahSoal: 140,
    status: "Closed",
    waktu: "120",
    tanggal: "10 Agustus 2025",
  },
  {
    name: "Try Out Kimia",
    jumlahSoal: 100,
    status: "Open",
    waktu: "90",
    tanggal: "12 Agustus 2025",
  },
  {
    name: "Try Out Sejarah",
    jumlahSoal: 100,
    status: "Hold",
    waktu: "80",
    tanggal: "14 Agustus 2025",
  },
  {
    name: "Try Out Bahasa Indonesia",
    jumlahSoal: 110,
    status: "Open",
    waktu: "100",
    tanggal: "15 Agustus 2025",
  },
  {
    name: "Try Out Ekonomi",
    jumlahSoal: 100,
    status: "Closed",
    waktu: "90",
    tanggal: "20 Agustus 2025",
  },
  {
    name: "Try Out IPS",
    jumlahSoal: 130,
    status: "Open",
    waktu: "100",
    tanggal: "23 Agustus 2025",
  },
  {
    name: "Try Out Geografi",
    jumlahSoal: 120,
    status: "Open",
    waktu: "90",
    tanggal: "25 Agustus 2025",
  },
  {
    name: "Try Out Matematika Lanjut",
    jumlahSoal: 150,
    status: "Closed",
    waktu: "120",
    tanggal: "27 Agustus 2025",
  },
  {
    name: "Try Out Kimia Organik",
    jumlahSoal: 140,
    status: "Hold",
    waktu: "110",
    tanggal: "1 September 2025",
  },
  {
    name: "Try Out Fisika Lanjut",
    jumlahSoal: 150,
    status: "Open",
    waktu: "120",
    tanggal: "5 September 2025",
  },
  {
    name: "Try Out Biologi Lanjut",
    jumlahSoal: 130,
    status: "Hold",
    waktu: "100",
    tanggal: "10 September 2025",
  },
  {
    name: "Try Out Matematika Inti",
    jumlahSoal: 120,
    status: "Closed",
    waktu: "90",
    tanggal: "15 September 2025",
  },
  {
    name: "Try Out Bahasa Inggris",
    jumlahSoal: 110,
    status: "Open",
    waktu: "90",
    tanggal: "20 September 2025",
  },
  {
    name: "Try Out Materi Teknik",
    jumlahSoal: 130,
    status: "Closed",
    waktu: "120",
    tanggal: "22 September 2025",
  },
  {
    name: "Try Out Teknik Informatika",
    jumlahSoal: 140,
    status: "Hold",
    waktu: "100",
    tanggal: "25 September 2025",
  },
  {
    name: "Try Out Sosial",
    jumlahSoal: 110,
    status: "Open",
    waktu: "90",
    tanggal: "30 September 2025",
  },
  {
    name: "Try Out Bahasa Jepang",
    jumlahSoal: 100,
    status: "Closed",
    waktu: "80",
    tanggal: "2 Oktober 2025",
  },
  {
    name: "Try Out Fisika Dasar",
    jumlahSoal: 130,
    status: "Open",
    waktu: "100",
    tanggal: "5 Oktober 2025",
  },
  {
    name: "Try Out Ekonomi Mikro",
    jumlahSoal: 120,
    status: "Open",
    waktu: "90",
    tanggal: "8 Oktober 2025",
  },
  {
    name: "Try Out Akuntansi",
    jumlahSoal: 110,
    status: "Hold",
    waktu: "100",
    tanggal: "10 Oktober 2025",
  },
  {
    name: "Try Out Biologi Terapan",
    jumlahSoal: 130,
    status: "Closed",
    waktu: "110",
    tanggal: "13 Oktober 2025",
  },
  {
    name: "Try Out Teknik Sipil",
    jumlahSoal: 120,
    status: "Open",
    waktu: "100",
    tanggal: "15 Oktober 2025",
  },
  {
    name: "Try Out Teknik Elektro",
    jumlahSoal: 150,
    status: "Closed",
    waktu: "120",
    tanggal: "17 Oktober 2025",
  },
  {
    name: "Try Out Ekonomi Makro",
    jumlahSoal: 100,
    status: "Open",
    waktu: "90",
    tanggal: "20 Oktober 2025",
  },
  {
    name: "Try Out Perpajakan",
    jumlahSoal: 110,
    status: "Hold",
    waktu: "80",
    tanggal: "22 Oktober 2025",
  },
  {
    name: "Try Out Biologi Genetika",
    jumlahSoal: 130,
    status: "Open",
    waktu: "100",
    tanggal: "25 Oktober 2025",
  },
  {
    name: "Try Out Kimia Dasar",
    jumlahSoal: 120,
    status: "Closed",
    waktu: "90",
    tanggal: "27 Oktober 2025",
  },
  {
    name: "Try Out Fisika Modern",
    jumlahSoal: 140,
    status: "Open",
    waktu: "100",
    tanggal: "2 November 2025",
  },
  {
    name: "Try Out Teknologi Informasi",
    jumlahSoal: 130,
    status: "Hold",
    waktu: "100",
    tanggal: "5 November 2025",
  },
  {
    name: "Try Out Komputer Dasar",
    jumlahSoal: 120,
    status: "Open",
    waktu: "90",
    tanggal: "8 November 2025",
  },
  {
    name: "Try Out Bahasa Arab",
    jumlahSoal: 110,
    status: "Closed",
    waktu: "80",
    tanggal: "10 November 2025",
  },
  {
    name: "Try Out PKN",
    jumlahSoal: 120,
    status: "Open",
    waktu: "90",
    tanggal: "12 November 2025",
  },
  {
    name: "Try Out Pendidikan Pancasila",
    jumlahSoal: 130,
    status: "Closed",
    waktu: "100",
    tanggal: "15 November 2025",
  },
  {
    name: "Try Out Hukum",
    jumlahSoal: 140,
    status: "Hold",
    waktu: "120",
    tanggal: "20 November 2025",
  },
  {
    name: "Try Out Kewirausahaan",
    jumlahSoal: 100,
    status: "Open",
    waktu: "90",
    tanggal: "23 November 2025",
  },
  {
    name: "Try Out Biologi Anatomi",
    jumlahSoal: 130,
    status: "Closed",
    waktu: "100",
    tanggal: "27 November 2025",
  },
  {
    name: "Try Out Geografi Lingkungan",
    jumlahSoal: 140,
    status: "Open",
    waktu: "120",
    tanggal: "2 Desember 2025",
  },
  {
    name: "Try Out Teknik Mesin",
    jumlahSoal: 100,
    status: "Hold",
    waktu: "90",
    tanggal: "5 Desember 2025",
  },
  {
    name: "Try Out Matematika Terapan",
    jumlahSoal: 120,
    status: "Closed",
    waktu: "100",
    tanggal: "10 Desember 2025",
  },
  {
    name: "Try Out Pendidikan Agama",
    jumlahSoal: 130,
    status: "Open",
    waktu: "90",
    tanggal: "12 Desember 2025",
  },
  {
    name: "Try Out Psikologi",
    jumlahSoal: 100,
    status: "Hold",
    waktu: "90",
    tanggal: "15 Desember 2025",
  },
  {
    name: "Try Out Fisika Teknik",
    jumlahSoal: 140,
    status: "Open",
    waktu: "110",
    tanggal: "20 Desember 2025",
  },
  {
    name: "Try Out Bioteknologi",
    jumlahSoal: 130,
    status: "Closed",
    waktu: "100",
    tanggal: "23 Desember 2025",
  },
  {
    name: "Try Out Ilmu Komunikasi",
    jumlahSoal: 120,
    status: "Open",
    waktu: "90",
    tanggal: "25 Desember 2025",
  },
  {
    name: "Try Out Manajemen",
    jumlahSoal: 110,
    status: "Closed",
    waktu: "100",
    tanggal: "30 Desember 2025",
  },
  {
    name: "Try Out Sosiologi",
    jumlahSoal: 130,
    status: "Open",
    waktu: "120",
    tanggal: "3 Januari 2026",
  },
  {
    name: "Try Out Sistem Informasi",
    jumlahSoal: 120,
    status: "Hold",
    waktu: "110",
    tanggal: "8 Januari 2026",
  },
  {
    name: "Try Out Logika Matematika",
    jumlahSoal: 100,
    status: "Open",
    waktu: "90",
    tanggal: "12 Januari 2026",
  },
  {
    name: "Try Out Statistik",
    jumlahSoal: 130,
    status: "Closed",
    waktu: "100",
    tanggal: "15 Januari 2026",
  },
  {
    name: "Try Out Pendidikan Matematika",
    jumlahSoal: 120,
    status: "Open",
    waktu: "90",
    tanggal: "18 Januari 2026",
  },
  {
    name: "Try Out Bahasa Perancis",
    jumlahSoal: 110,
    status: "Hold",
    waktu: "100",
    tanggal: "22 Januari 2026",
  },
  {
    name: "Try Out Fisika Kuantum",
    jumlahSoal: 140,
    status: "Closed",
    waktu: "120",
    tanggal: "25 Januari 2026",
  },
];
export default soalData;
