const UserData = [
  {
    nama: "John Doe",
    email: "john.doe@example.com",
    password: "password123",
    paket: "Premium",
  },
  {
    nama: "Jane Smith",
    email: "jane.smith@example.com",
    password: "securePass456",
    paket: "Gold",
  },
  {
    nama: "Michael Johnson",
    email: "michael.johnson@example.com",
    password: "michael789",
    paket: "Silver",
  },
  {
    nama: "Emily Davis",
    email: "emily.davis@example.com",
    password: "emily@123",
    paket: "Diamond",
  },
  {
    nama: "David Williams",
    email: "david.williams@example.com",
    password: "david321",
    paket: "Gold",
  },
  {
    nama: "Sophia Lee",
    email: "sophia.lee@example.com",
    password: "sophia@456",
    paket: "Silver",
  },
  {
    nama: "Daniel Brown",
    email: "daniel.brown@example.com",
    password: "daniel789",
    paket: "Premium",
  },
  {
    nama: "Olivia Miller",
    email: "olivia.miller@example.com",
    password: "olivia@pass",
    paket: "Diamond",
  },
  {
    nama: "Liam Anderson",
    email: "liam.anderson@example.com",
    password: "liam@321",
    paket: "Gold",
  },
  {
    nama: "Ava Wilson",
    email: "ava.wilson@example.com",
    password: "ava12345",
    paket: "Silver",
  },
  {
    nama: "Lucas Moore",
    email: "lucas.moore@example.com",
    password: "lucas@2023",
    paket: "Premium",
  },
  {
    nama: "Mia Taylor",
    email: "mia.taylor@example.com",
    password: "mia@secure",
    paket: "Gold",
  },
  {
    nama: "Ethan Jackson",
    email: "ethan.jackson@example.com",
    password: "ethan@987",
    paket: "Diamond",
  },
  {
    nama: "Isabella Martinez",
    email: "isabella.martinez@example.com",
    password: "isabella@pass",
    paket: "Silver",
  },
  {
    nama: "James Harris",
    email: "james.harris@example.com",
    password: "james456",
    paket: "Premium",
  },
  {
    nama: "Charlotte Clark",
    email: "charlotte.clark@example.com",
    password: "charlotte@789",
    paket: "Gold",
  },
  {
    nama: "Benjamin Lewis",
    email: "benjamin.lewis@example.com",
    password: "benjamin@123",
    paket: "Silver",
  },
  {
    nama: "Amelia Robinson",
    email: "amelia.robinson@example.com",
    password: "amelia@321",
    paket: "Diamond",
  },
  {
    nama: "Oliver Walker",
    email: "oliver.walker@example.com",
    password: "oliver@111",
    paket: "Gold",
  },
  {
    nama: "Evelyn Young",
    email: "evelyn.young@example.com",
    password: "evelyn123",
    paket: "Silver",
  },
  {
    nama: "Jack Allen",
    email: "jack.allen@example.com",
    password: "jack@pass",
    paket: "Premium",
  },
  {
    nama: "Harper Scott",
    email: "harper.scott@example.com",
    password: "harper@2023",
    paket: "Gold",
  },
  {
    nama: "Mason King",
    email: "mason.king@example.com",
    password: "mason@456",
    paket: "Diamond",
  },
  {
    nama: "Lily Wright",
    email: "lily.wright@example.com",
    password: "lily1234",
    paket: "Silver",
  },
  {
    nama: "Alexander Gonzalez",
    email: "alexander.gonzalez@example.com",
    password: "alexander@123",
    paket: "Premium",
  },
  {
    nama: "Ella Perez",
    email: "ella.perez@example.com",
    password: "ella@pass",
    paket: "Gold",
  },
  {
    nama: "Sebastian Lee",
    email: "sebastian.lee@example.com",
    password: "sebastian@2023",
    paket: "Diamond",
  },
  {
    nama: "Zoe Carter",
    email: "zoe.carter@example.com",
    password: "zoe@123",
    paket: "Silver",
  },
  {
    nama: "Matthew Mitchell",
    email: "matthew.mitchell@example.com",
    password: "matthew@456",
    paket: "Gold",
  },
  {
    nama: "Sophie Nelson",
    email: "sophie.nelson@example.com",
    password: "sophie123",
    paket: "Premium",
  },
  {
    nama: "Chloe Roberts",
    email: "chloe.roberts@example.com",
    password: "chloe@secure",
    paket: "Diamond",
  },
  {
    nama: "Jacob Evans",
    email: "jacob.evans@example.com",
    password: "jacob1234",
    paket: "Silver",
  },
  {
    nama: "Grace Walker",
    email: "grace.walker@example.com",
    password: "grace456",
    paket: "Gold",
  },
  {
    nama: "Samuel Hernandez",
    email: "samuel.hernandez@example.com",
    password: "samuel@pass",
    paket: "Premium",
  },
  {
    nama: "Mila Carter",
    email: "mila.carter@example.com",
    password: "mila@789",
    paket: "Diamond",
  },
  {
    nama: "Wyatt Turner",
    email: "wyatt.turner@example.com",
    password: "wyatt321",
    paket: "Gold",
  },
  {
    nama: "Victoria Adams",
    email: "victoria.adams@example.com",
    password: "victoria@123",
    paket: "Silver",
  },
  {
    nama: "Isaiah Perez",
    email: "isaiah.perez@example.com",
    password: "isaiah@2023",
    paket: "Premium",
  },
  {
    nama: "Amos Reed",
    email: "amos.reed@example.com",
    password: "amos@secure",
    paket: "Gold",
  },
  {
    nama: "Landon Simmons",
    email: "landon.simmons@example.com",
    password: "landon@pass",
    paket: "Diamond",
  },
  {
    nama: "Nina Foster",
    email: "nina.foster@example.com",
    password: "nina@pass",
    paket: "Silver",
  },
  {
    nama: "Carter Bell",
    email: "carter.bell@example.com",
    password: "carter@123",
    paket: "Gold",
  },
  {
    nama: "Aidan Green",
    email: "aidan.green@example.com",
    password: "aidan1234",
    paket: "Premium",
  },
  {
    nama: "Violet Edwards",
    email: "violet.edwards@example.com",
    password: "violet@pass",
    paket: "Diamond",
  },
  {
    nama: "Henry Morris",
    email: "henry.morris@example.com",
    password: "henry@2023",
    paket: "Gold",
  },
  {
    nama: "Archer Collins",
    email: "archer.collins@example.com",
    password: "archer@secure",
    paket: "Silver",
  },
  {
    nama: "Zara Long",
    email: "zara.long@example.com",
    password: "zara@789",
    paket: "Diamond",
  },
  {
    nama: "Ethan Mitchell",
    email: "ethan.mitchell@example.com",
    password: "ethan321",
    paket: "Premium",
  },
  {
    nama: "Jaxon Peterson",
    email: "jaxon.peterson@example.com",
    password: "jaxon@123",
    paket: "Gold",
  },
  {
    nama: "Lila Sanchez",
    email: "lila.sanchez@example.com",
    password: "lila@secure",
    paket: "Silver",
  },
  {
    nama: "Miles Rivera",
    email: "miles.rivera@example.com",
    password: "miles@2023",
    paket: "Diamond",
  },
  {
    nama: "Levi Bailey",
    email: "levi.bailey@example.com",
    password: "levi1234",
    paket: "Gold",
  },
  {
    nama: "Ariana Brooks",
    email: "ariana.brooks@example.com",
    password: "ariana@321",
    paket: "Silver",
  },
  {
    nama: "Harper Gray",
    email: "harper.gray@example.com",
    password: "harper@pass",
    paket: "Diamond",
  },
  {
    nama: "Maximus Lee",
    email: "maximus.lee@example.com",
    password: "maximus@2023",
    paket: "Premium",
  },
  {
    nama: "Leila Howard",
    email: "leila.howard@example.com",
    password: "leila123",
    paket: "Gold",
  },
  {
    nama: "Jesse Ward",
    email: "jesse.ward@example.com",
    password: "jesse@pass",
    paket: "Silver",
  },
  {
    nama: "Nolan James",
    email: "nolan.james@example.com",
    password: "nolan@456",
    paket: "Diamond",
  },
];

export default UserData;
