const VideoData = [
  { nama: "Pengenalan Farmasi Klinik", status: "open" },
  { nama: "Farmakologi Dasar", status: "hold" },
  { nama: "Penyuluhan Obat kepada Pasien", status: "closed" },
  { nama: "Mengenal Obat Generik dan Obat Bermerek", status: "open" },
  { nama: "Prinsip-Prinsip Pengobatan yang Rasional", status: "closed" },
  { nama: "Peran Apoteker dalam Layanan Kesehatan", status: "hold" },
  { nama: "Pengelolaan Obat di Rumah Sakit", status: "open" },
  { nama: "Interaksi Obat dan Efek Samping", status: "closed" },
  { nama: "Farmasi Komunitas dan Praktiknya", status: "hold" },
  { nama: "Penyimpanan dan Pengelolaan Obat", status: "open" },
  { nama: "Manajemen Resiko dalam Penggunaan Obat", status: "closed" },
  { nama: "Farmasi Industri: Produksi Obat", status: "open" },
  { nama: "Kebijakan Kesehatan dan Farmasi", status: "hold" },
  { nama: "Teknologi Farmasi Terkini", status: "closed" },
  { nama: "Klinik Farmasi dalam Praktek Medis", status: "open" },
  { nama: "Farmasi untuk Penyakit Kronis", status: "hold" },
  { nama: "Farmasi Anak dan Bayi", status: "closed" },
  { nama: "Asuhan Farmasi pada Penyakit Infeksi", status: "open" },
  { nama: "Farmakokinetik dan Farmakodinamik", status: "closed" },
  { nama: "Manajemen Obat dalam Keadaan Darurat", status: "open" },
  { nama: "Etika dan Hukum dalam Praktik Farmasi", status: "closed" },
  { nama: "Penyakit Kardiovaskular dan Pengobatannya", status: "hold" },
  { nama: "Farmasi dalam Penanganan Kanker", status: "open" },
  { nama: "Penggunaan Obat Terhadap Lansia", status: "closed" },
  { nama: "Farmasi dan Sistem Kesehatan Global", status: "hold" },
  { nama: "Penyakit Tropis dan Obat-obatan", status: "open" },
  { nama: "Penggunaan Obat di Era Pandemi", status: "closed" },
  { nama: "Farmasi dalam Kesehatan Mental", status: "open" },
  { nama: "Obat Anti-Mikroba dan Resistansi", status: "hold" },
  { nama: "Pemantauan Terapi Obat", status: "closed" },
  { nama: "Penelitian dan Pengembangan Obat", status: "open" },
  { nama: "Obat dan Terapi untuk Penyakit Autoimun", status: "closed" },
  { nama: "Pendidikan Farmasi untuk Masyarakat", status: "open" },
  { nama: "Pendekatan Holistik dalam Terapi Obat", status: "hold" },
  { nama: "Farmasi di Era Digital", status: "open" },
  { nama: "Terapi Gen dalam Farmasi", status: "closed" },
  { nama: "Keamanan Obat dan Regulasi", status: "open" },
  { nama: "Farmasi Komunitas dalam Penanganan Diabetes", status: "closed" },
  { nama: "Penyuluhan dan Pendidikan Kesehatan oleh Apoteker", status: "hold" },
  { nama: "Penyakit Infeksi dan Pengobatannya", status: "open" },
  { nama: "Manajemen Stres dengan Obat-obatan", status: "closed" },
  { nama: "Farmasi dan Inovasi dalam Penyakit Menular", status: "open" },
  { nama: "Obat dalam Penanganan Gangguan Hormon", status: "hold" },
  { nama: "Aplikasi Teknologi dalam Praktik Farmasi", status: "closed" },
  { nama: "Strategi Pengelolaan Obat di Apotek", status: "open" },
  { nama: "Farmasi dan Kesehatan Gigi", status: "closed" },
];

export default VideoData;
